### ISSUE TITLE
Voucher prefixes

### ISSUE THREAD

**Issue by ozrouter** [mcmilk/UniFi-HotSpot-Manager#10]
You mention "different Usergroups via Voucher prefixes"

how is this implemented?

**Comment by mcmilk** [comment]
You can add multiple users, and give each of them some own prefix. Each "Hotspot-Manager user" will see only his own vouchers - where the prefix is the correct one.

The admin user will see all vouchers ...

**Comment by ozrouter** [comment]
ok cool thanks,

I had found Unifi vouchers are rather limited.
