### ISSUE TITLE
Issue with the JSON

### ISSUE THREAD

**Issue by just-hot** [mcmilk/UniFi-HotSpot-Manager#11]
Hi mcmilk,

I receive the following error on the unifi page can you help me to fix it? I have redownload your files and setup the config file but still the same. I run the script on ubuntu with xampp. When I create a voucher it will show in the unifi controler but not on the page vouchers then it will give this error: 

DataTables warning: table id=myTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by mcmilk** [comment]
Will be fixed within some weeks ... sorry for the very long delay ;)
