### ISSUE TITLE
Printen op ESC/POS

### ISSUE THREAD

**Issue by just-hot** [mcmilk/UniFi-HotSpot-Manager#6]
Goedenavond @mcmilk ,

Bedankt voor het script! Is het ook mogelijk om een optie te maken om te printen naar een terminal printer?

Alvast bedankt

**Comment by mcmilk** [comment]
Hello, english comments would be better ;-)

And of cause, there should be no problem with your question. The generated PDF has to be adjusted to fit your new "page size" ... thats it.

Can you give me the name of your device, I can help you with that then.

**Comment by just-hot** [comment]
Hi @mcmilk ,

It is a Epson TM-T88III

Thanks in advance

**Comment by mcmilk** [comment]
Sorry for the late reply, I have checked it ... and it's not that easy to to add support for that printer
